import os
import google.auth
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

def upload_to_youtube(video_path, script_text):
    title = script_text.split("\n")[0].replace("HOOK:", "").strip()
    description = "Generated by AutoViral Shorts Machine"
    tags = ["AI", "Money", "Viral", "MrBeast", "Shorts"]
    category_id = "22"  # People & Blogs

    creds, _ = google.auth.default(scopes=["https://www.googleapis.com/auth/youtube.upload"])
    youtube = build("youtube", "v3", credentials=creds)

    request_body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags,
            "categoryId": category_id
        },
        "status": {
            "privacyStatus": "public",  # or 'private', 'unlisted'
        }
    }

    media_file = MediaFileUpload(video_path, mimetype="video/mp4", resumable=True)

    request = youtube.videos().insert(
        part="snippet,status",
        body=request_body,
        media_body=media_file
    )
    response = request.execute()
    print(f"✅ Uploaded to YouTube: https://youtube.com/watch?v={response['id']}")
